export 'alarme.dart' show alarme;
export 'pararalarme.dart' show pararalarme;
export 'apagar_tela.dart' show apagarTela;
export 'pararalarme_copy.dart' show pararalarmeCopy;
export 'pararalarme_copy2.dart' show pararalarmeCopy2;
export 'ascender_tela.dart' show ascenderTela;
export 'check_android_schedule_exact_alarm_permission.dart'
    show checkAndroidScheduleExactAlarmPermission;
export 'solicitar_permissao.dart' show solicitarPermissao;
export 'inicializar_alarm.dart' show inicializarAlarm;
export 'redirecionar_pagina.dart' show redirecionarPagina;
export 'desliga_tela.dart' show desligaTela;
export 'inicializar_wakelok.dart' show inicializarWakelok;
export 'sobrepor.dart' show sobrepor;
export 'wakelockplugin001.dart' show wakelockplugin001;
export 'local_notification.dart' show localNotification;
export 'ativa_tela.dart' show ativaTela;
export 'redirecionar_pagina_copy.dart' show redirecionarPaginaCopy;
export 'liga_tela.dart' show ligaTela;
export 'criar_alarme.dart' show criarAlarme;
export 'full_escreen.dart' show fullEscreen;
export 'segundo_plano.dart' show segundoPlano;
